services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ml-template-backend
    ports:
      - "8000:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        VITE_API_BASE_URL: http://localhost:8000
    container_name: ml-template-frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
