export const MARITAL_STATUS: Record<number, string> = {
  1: 'Single',
  2: 'Married',
  3: 'Widower',
  4: 'Divorced',
  5: 'Facto union',
  6: 'Legally separated',
}

export const APPLICATION_MODE: Record<number, string> = {
  1: '1st phase — general contingent',
  2: 'Ordinance No. 612/93',
  5: '1st phase — special contingent (Azores)',
  7: 'Holders of other higher courses',
  10: 'Ordinance No. 854-B/99',
  15: 'International student (bachelor)',
  16: '1st phase — special contingent (Madeira)',
  17: '2nd phase — general contingent',
  18: '3rd phase — general contingent',
  26: 'Ordinance No. 533-A/99, item b2 (different plan)',
  27: 'Ordinance No. 533-A/99, item b3 (other institution)',
  39: 'Over 23 years old',
  42: 'Transfer',
  43: 'Change of course',
  44: 'Technological specialization diploma holders',
  51: 'Change of institution/course',
  53: 'Short cycle diploma holders',
  57: 'Change of institution/course (international)',
}

export const COURSE: Record<number, string> = {
  33: 'Biofuel Production Technologies',
  171: 'Animation and Multimedia Design',
  8014: 'Social Service (evening attendance)',
  9003: 'Agronomy',
  9070: 'Communication Design',
  9085: 'Veterinary Nursing',
  9119: 'Informatics Engineering',
  9130: 'Equinculture',
  9147: 'Management',
  9238: 'Social Service',
  9254: 'Tourism',
  9500: 'Nursing',
  9556: 'Oral Hygiene',
  9670: 'Advertising and Marketing Management',
  9773: 'Journalism and Communication',
  9853: 'Basic Education',
  9991: 'Management (evening attendance)',
}

export const PREVIOUS_QUALIFICATION: Record<number, string> = {
  1: 'Secondary education',
  2: "Higher education — bachelor's degree",
  3: 'Higher education — degree',
  4: "Higher education — master's",
  5: 'Higher education — doctorate',
  6: 'Frequency of higher education',
  9: '12th year of schooling — not completed',
  10: '11th year of schooling — not completed',
  12: 'Other — 11th year of schooling',
  14: '10th year of schooling',
  15: '10th year of schooling — not completed',
  19: 'Basic education 3rd cycle (9th/10th/11th year) or equiv.',
  38: 'Basic education 2nd cycle (6th/7th/8th year) or equiv.',
  39: 'Technological specialization course',
  40: 'Higher education — degree (1st cycle)',
  42: 'Professional higher technical course',
  43: 'Higher education — master (2nd cycle)',
}

export const NATIONALITY: Record<number, string> = {
  1: 'Portuguese',
  2: 'German',
  6: 'Spanish',
  11: 'Italian',
  13: 'Dutch',
  14: 'English',
  17: 'Lithuanian',
  21: 'Angolan',
  22: 'Cape Verdean',
  24: 'Guinean',
  25: 'Mozambican',
  26: 'Santomean',
  32: 'Turkish',
  41: 'Brazilian',
  62: 'Romanian',
  100: 'Moldovan',
  101: 'Mexican',
  103: 'Ukrainian',
  105: 'Russian',
  108: 'Cuban',
  109: 'Colombian',
}

export const PARENT_QUALIFICATION: Record<number, string> = {
  1: 'Secondary Education — 12th year or equivalent',
  2: "Higher Education — bachelor's degree",
  3: 'Higher Education — degree',
  4: "Higher Education — master's",
  5: 'Higher Education — doctorate',
  6: 'Frequency of Higher Education',
  9: '12th year of schooling — not completed',
  10: '11th year of schooling — not completed',
  11: '7th year (old)',
  12: 'Other — 11th year of schooling',
  13: '2nd year complementary high school course',
  14: '10th year of schooling',
  18: 'General commerce course',
  19: 'Basic education 3rd cycle (9th/10th/11th year) or equiv.',
  20: 'Complementary high school course',
  22: 'Technical-professional course',
  25: 'Complementary high school course — not concluded',
  26: '7th year of schooling',
  27: '2nd cycle of the general high school course',
  29: '9th year of schooling — not completed',
  30: '8th year of schooling',
  31: 'General course of administration and commerce',
  33: 'Supplementary accounting and administration',
  34: 'Unknown',
  35: "Can't read or write",
  36: 'Can read without a 4th year of schooling',
  37: 'Basic education 1st cycle (4th/5th year) or equiv.',
  38: 'Basic education 2nd cycle (6th/7th/8th year) or equiv.',
  39: 'Technological specialization course',
  40: 'Higher education — degree (1st cycle)',
  41: 'Specialized higher studies course',
  42: 'Professional higher technical course',
  43: 'Higher Education — master (2nd cycle)',
  44: 'Higher Education — doctorate (3rd cycle)',
}

export const PARENT_OCCUPATION: Record<number, string> = {
  0: 'Student',
  1: 'Legislative/executive directors and managers',
  2: 'Specialists in intellectual and scientific activities',
  3: 'Intermediate level technicians and professions',
  4: 'Administrative staff',
  5: 'Personal services, security and safety workers, sellers',
  6: 'Farmers and skilled agriculture/fishery/forestry workers',
  7: 'Skilled industry, construction and craft workers',
  8: 'Installation and machine operators, assembly workers',
  9: 'Unskilled workers',
  10: 'Armed forces professions',
  90: 'Other situation',
  99: '(blank)',
  101: 'Armed forces officers',
  102: 'Armed forces sergeants',
  103: 'Other armed forces personnel',
  112: 'Directors of administrative and commercial services',
  114: 'Hotel, catering, trade and other services directors',
  121: 'Specialists in physical sciences, math and engineering',
  122: 'Health professionals',
  123: 'Teachers',
  124: 'Finance, accounting and administrative specialists',
  125: 'Specialists in information and communication technologies',
  131: 'Intermediate science and engineering technicians',
  132: 'Intermediate level health technicians',
  134: 'Intermediate legal/social/sports/cultural technicians',
  135: 'Information and communication technology technicians',
  141: 'Office workers and secretaries',
  143: 'Data, accounting and financial services operators',
  144: 'Other administrative support staff',
  151: 'Personal service workers',
  152: 'Sellers',
  153: 'Personal care workers and the like',
  154: 'Protection and security services personnel',
  161: 'Market-oriented farmers and skilled agricultural workers',
  163: 'Farmers, livestock keepers, fishermen, hunters, subsistence',
  171: 'Skilled construction workers (except electricians)',
  172: 'Skilled workers in metallurgy and metalworking',
  173: 'Skilled workers in printing, precision instruments, crafts',
  174: 'Skilled workers in electricity and electronics',
  175: 'Food processing, woodworking and clothing industry workers',
  181: 'Fixed plant and machine operators',
  182: 'Assembly workers',
  183: 'Vehicle drivers and mobile equipment operators',
  191: 'Cleaning workers',
  192: 'Unskilled agriculture/animal production/fishery workers',
  193: 'Unskilled extractive/construction/transport workers',
  194: 'Meal preparation assistants',
  195: 'Street vendors and street service providers',
}

export const CATEGORY_LABELS: Record<string, Record<number, string>> = {
  'Marital status': MARITAL_STATUS,
  Nationality: NATIONALITY,
  'Application mode': APPLICATION_MODE,
  Course: COURSE,
  'Previous qualification': PREVIOUS_QUALIFICATION,
  "Mother's qualification": PARENT_QUALIFICATION,
  "Father's qualification": PARENT_QUALIFICATION,
  "Mother's occupation": PARENT_OCCUPATION,
  "Father's occupation": PARENT_OCCUPATION,
}

export const BINARY_LABELS: Record<string, [string, string]> = {
  'Daytime/evening attendance': ['Evening', 'Daytime'],
  Displaced: ['No', 'Yes'],
  'Educational special needs': ['No', 'Yes'],
  Debtor: ['No', 'Yes'],
  'Tuition fees up to date': ['No', 'Yes'],
  Gender: ['Female', 'Male'],
  'Scholarship holder': ['No', 'Yes'],
  International: ['No', 'Yes'],
}
